name: Release

on:
  push:
    tags:
      - "*-agent/v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Extract agent name
        id: extract
        run: |
          AGENT=$(echo ${{ github.ref_name }} | awk -F'/' '{print $1}')
          echo "AGENT=$AGENT" >> $GITHUB_ENV

      - uses: goreleaser/goreleaser-action@v6
        with:
          workdir: ${{ env.AGENT }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}